### ISSUE TITLE
Automatic reboot to bootloader

### ISSUE THREAD

**Issue by davcri** [luca020400/Moto-G-2014-ToolKit#5]
With **adb** is possible to reboot to bootloader without user input. I do that with this command :  

```
adb reboot-bootloader
```

Is it safe to put this in the scripts ? In this way users don't need to manually restart the phone. I actually use this commando because I'm very lazy and I don't want my hands leave the keyboard :smile:

**Comment by luca020400** [comment]
Check dev branch
